#!/bin/sh

# Run some pre commit checks on the Go source code. Prevent the commit if any errors are found
echo -e "\nRunning pre-commit checks on your code...\n"
./scripts/code-check.sh
./scripts/eslint-check.sh