# .goreleaser.yml
# Build customization
builds:
  # makefile currently relies on this name
  - binary: mobile-security-service
    main: ./cmd/mobile-security-service/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  