version: '3'

services:
  db:
    image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USER: postgresql
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_DATABASE: mobile_security_service
  api:
    build: .
    environment:
      PGHOST: db
      PGUSER: postgresql
      PGPASSWORD: postgres
      PGDATABASE: mobile_security_service
    ports:
      - "3000:3000"
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui:v3.0.5
    ports:
      - 8080:8080
    environment:
      API_URL: https://raw.githubusercontent.com/aerogear/mobile-security-service/master/api/swagger.yaml