# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/aerogear/mobile-security-service

    docker:
      - image: circleci/golang:1.10
      - image: registry.access.redhat.com/rhscl/postgresql-96-rhel7:latest
        ports:
          - 5432:5432
        environment:
          POSTGRESQL_PASSWORD: postgres
          POSTGRESQL_USER: postgresql
          POSTGRESQL_DATABASE: mobile_security_service
    
    steps:
      - checkout
      - run: ./scripts/commit-filter-check.sh 
      - run: go get github.com/mattn/goveralls
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make build
      - run: make test-unit
      - run: make test-integration-cover
      - run: /go/bin/goveralls -coverprofile=coverage-all.out -service=circle-ci -repotoken=IccwXNeC1niB17Du1tCWu8LA0wd7uBbCh

  docker_push_master:
    working_directory: /go/src/github.com/aerogear/mobile-security-service
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make setup
      - setup_remote_docker
      - run: make build_linux
      - run: make docker_build_master
      - run: make docker_push_master

  docker_release:
    working_directory: /go/src/github.com/aerogear/mobile-security-service
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make setup
      - run: curl -sL https://raw.githubusercontent.com/goreleaser/get/master/get | bash
      - setup_remote_docker
      - run: make docker_build_release
      - run: make docker_push_release
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /\d{1,2}\.\d{1,2}\.\d{1,2}/
            branches:
              ignore: /.*/