ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

= Mobile Security Service UI

ifdef::status[]
.*Project health*
image:https://circleci.com/gh/aerogear/mobile-security-service.svg?style=svg[Build Status (CircleCI), link=https://circleci.com/gh/aerogear/mobile-security-service]
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
endif::[]

:toc:
toc::[]

== Getting Started

=== Prerequisites

Minimum node version: 10

=== Run the Server

To run the app in the development mode on localhost:3000 run:

[source,shell]
----
npm start
----

Running the server and the web UI together from the Mobile-Security-Service project root run
[source,shell]
----
make serve
----

=== Run in VSCode debug mode

The following steps are specific to VSCode, however you can run the project in any editor:

. Open the project in VSCode
. Run in debug mode

TIP: Read how to configure VSCode chrome debugger https://code.visualstudio.com/docs/nodejs/reactjs-tutorial#_debugging-react[here].

=== Testing

To run tests locally run:
[source,shell]
----
npm test
----

Follow the output in order to run the desired test

== Setup and configurations

=== Environment Variables

The **mobile-security-service** web application is configured using environment variables.

* By default, the application will look for system environment variables to use.
* If a system environment variable cannot be found, the application will then check the `.env` file in the application root.
* If the `.env` file does not exist, or if the variable is not defined in the file, the application will use the default value defined in link:./src/config/config.js[config.js].

NOTE: React applications can only read environment variables that are prefixed with `REACT_APP_`.

=== Adding your own .env file

Make a copy of the example file `.env.example`:

[source,shell]
----
cp .env.example .env
----

Now the application will use the values defined in `.env`.

=== Configuration

|===
| *Variable* | *Default* | *Description*
| REACT_APP_API_URL                             | /api    | The base URL of the Mobile Security Service REST API
| REACT_APP_NAME                        | Mobile Security Service    | The display name of the web application
|===

== A note on testing packages

Tests are written using two packages

* https://jestjs.io[Jest]
* Enzyme

Enzyme is used to https://airbnb.io/enzyme/docs/api/shallow.html#shallow-rendering-api[shallow render] components in order to unit test
Jest is used for running the tests. e.g. [expect|https://jestjs.io/docs/en/expect].

TIP: Read more on testing using react-scripts https://facebook.github.io/create-react-app/docs/running-tests[here].

NOTE: This project was bootstrapped with https://github.com/facebook/create-react-app[Create React App].